---
title: "KORA-AMD"
author: "Matina Kasiouri, Sven Morlock, Leo Höltkemeyer"
date: "2023-03-20"
output:
  pdf_document:
    includes:
      header-includes:
      - \usepackage{caption}
      - \usepackage{booktabs}
      - \usepackage{longtable}
      - \usepackage{array}
      - \usepackage{multirow}
      - \usepackage{wrapfig}
      - \usepackage{float}
      - \usepackage{colortbl}
      - \usepackage{pdflscape}
      - \usepackage{tabu}
      - \usepackage{threeparttable}
      - \usepackage{threeparttablex}
      - \usepackage[normalem]{ulem}
      - \usepackage{makecell}
      - \usepackage{xcolor}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(warn = -1) 
```

```{r preliminaries, warning=FALSE}
source("preprocess.R")
library(kableExtra)
library(broom)
```

```{r define-functions, echo = FALSE, include = FALSE}
my_kable <- function(dtbl, caption, booktabs = TRUE, col.names = NULL, latex_options = "hold_position", expo = FALSE) {
  #'
  #' @dtbl (data.table): data table to be written in table form.
  #' @caption (chr): cation of table.
  #' @booktabs (logical): passed to same param in kable
  #' @col.names (logical): passed to same param in kable
  #' @latex_options (chr): passed to same param in kable
  #' @expo (logical): if 'TRUE' all numeric columns will be exponentiated to base e.
  #'
  #'
  assertDataTable(dtbl)
  assertString(caption)
  assertString(latex_options)
  assertLogical(booktabs)
  assertLogical(expo)
  if (expo) {
    cols_numeric <- names(sapply(dtbl, is.numeric))[sapply(dtbl, is.numeric)]
    dtbl[, (cols_numeric) := lapply(.SD, exp), .SDcols = cols_numeric]
  }
  kable(dtbl,
        caption = caption,
        booktabs = booktabs,
        col.names = col.names)
} %>%  kable_styling(latex_options = latex_options)
```

# I Deskriptive Statstik

### §1 Allgemein
```{r fit-amd-bl}
as.data.table(table(data_fit[, LT_conti_worst_eye], useNA = "always")) %>% 
  my_kable(caption = "FIT: AMD at BL")
```

```{r fit-amd-fu}
as.data.table(table(data_fit[, PT_conti_worst_eye],useNA = "always")) %>% 
  my_kable(caption = "FIT: AMD at FU")
```

```{r fit-amd-fu-1}
as.data.table(table(data_fit[LT_conti_worst_eye == "no_amd", PT_conti_worst_eye], useNA = "always")) %>% 
  my_kable(caption = "FIT: AMD at FU (no AMD at BL)")
```

```{r fit-amd-fu-2}
as.data.table(table(data_fit[LT_conti_worst_eye == "no_amd" | LT_conti_worst_eye == "early", PT_conti_worst_eye],useNA = "always")) %>% 
  my_kable(caption = "FIT: AMD at FU (no AMD or early AMD at BL)")
```
\newpage
### §2 Inzidenz und Progression

```{r fit-incidence, echo = FALSE, include = FALSE}
incidences_fit <- get_incidence_tbl(data_fit,
                  amd_bl_col = "LT_conti_worst_eye",
                  amd_fu_col = "PT_conti_worst_eye",
                  split_col = "age_group_fit")
```

```{r fit-incidence-case1}
incidences_fit[["case1"]] %>% 
  my_kable(caption = "Cummulative incidence of early AMD", col.names = NA)
```

```{r fit-incidence-case2}
incidences_fit[["case2"]] %>% 
  my_kable(caption = "Cummulative incidence of late AMD (definition 1)", col.names = NA)
```

```{r fit-incidence-case3}
incidences_fit[["case3"]] %>% 
  my_kable(caption= "Cummulative incidence of late AMD (definition 2)", col.names = NA)
```

```{r fit-incidence-case4}
incidences_fit[["case4"]] %>% 
  my_kable(caption = "Cummulative progression from early to late AMD", col.names = NA)
```
\newpage
# II Logistische Modelle
```{r analysis-one-eye}
source("analysis-one-eye-conti.R")
```

## §1 pro Proband (schlechteste Auge)
```{r fit-case-1}
my_kable(
  as.data.table(tidy(model_fit_1)),
  caption = "Modell1 (Inzidenz Frühe AMD, exp)",
  col.names = NA,
  expo = TRUE
)
```

```{r fit-case-2}
my_kable(
  as.data.table(tidy(model_fit_2)),
  caption = "Modell2 (Inzidenz späte AMD (Def. 1), exp)",
  col.names = NA,
  expo = TRUE
)
```

```{r fit-case-3}
my_kable(
  as.data.table(tidy(model_fit_3)),
  caption = "Modell3(Inzidenz späte AMD (Def. 2), exp)",
  col.names = NA,
  expo = TRUE
)
```

```{r fit-case-4}
my_kable(
  as.data.table(tidy(model_fit_4)),
  caption = "Modell4 (Progression frühe/späte AMD, exp)",
  col.names = NA,
  expo = TRUE
)
```
\newpage
## §2 pro Auge
```{r, echo=FALSE, include=FALSE}
source("analysis-two-eyes-conti.R")
```

```{r fit-marginal-case-1}
my_kable(
  tidy_gee(model_gee_fit_1),
  caption = "GEE Modell 1",
  col.names = NA
)
```

```{r}

```